### ISSUE TITLE
Implement Console

### ISSUE THREAD

**Issue by JEPPSER** [JEPPSER/1DV607-MVC#4]

**Comment by brokenprogrammer** [comment]
1. View All Members
2. View All Member Verbose
3. Create Member (Name, Personal Number)
4. Update Member (Id)
5. Delete Member (Id)
6. View Member (Id)
7. Create Boat (Type, Length)
8. Update Boat (MemberId.., BoatNumber(In MemberList?), Boat)
9. Delete Boat (MemberId.., BoatNumber(In MemberList?), Boat)
10. View Boat  (MemberId.., BoatNumber(In MemberList?), Boat)
